// Seed data for Firebase Firestore
export const seedData = {
  users: [
    {
      id: "usr_admin",
      name: "Mukasa David",
      email: "admin@agrobridge.com",
      passwordHash: "admin123", // Will need to be hashed on seed
      phone: "+256 772 123456",
      role: "admin",
      verificationStatus: "verified",
      createdAt: new Date().toISOString(),
    },
    {
      id: "usr_agent1",
      name: "Nsubuga Peter",
      email: "agent1@agrobridge.com",
      passwordHash: "agent123",
      phone: "+256 782 987654",
      role: "agent",
      verificationStatus: "verified",
      createdAt: new Date().toISOString(),
    },
    {
      id: "usr_agent2",
      name: "Aisha Kamara",
      email: "agent2@agrobridge.com",
      passwordHash: "agent123",
      phone: "+256 752 444555",
      role: "agent",
      verificationStatus: "verified",
      createdAt: new Date().toISOString(),
    },
    {
      id: "usr_buyer1",
      name: "Sarah Namubiru",
      email: "buyer@agrobridge.com",
      passwordHash: "buyer123",
      phone: "+256 701 111222",
      role: "buyer",
      verificationStatus: "verified",
      createdAt: new Date().toISOString(),
    },
  ],
  agents: [
    {
      userId: "usr_agent1",
      nationalId: "NIN-UG-19887722A",
      serviceArea: "Mityana & Wakiso Districts",
      approvalStatus: "approved",
    },
    {
      userId: "usr_agent2",
      nationalId: "NIN-UG-19942233B",
      serviceArea: "Luweero Rural Cooperatives",
      approvalStatus: "approved",
    },
  ],
  farmers: [
    {
      id: "farm_1",
      agentId: "usr_agent1",
      name: "John Ssekandi",
      village: "Kikandwa Village",
      location: "Mityana",
      phone: "+256 774 000111",
      farmSize: "4.5",
      cropTypes: ["Matooke", "Coffee", "Cassava"],
      notes: "Ssekandi is a third-generation coffee and banana farmer.",
      createdAt: new Date().toISOString(),
      status: "active",
    },
    {
      id: "farm_2",
      agentId: "usr_agent1",
      name: "Grace Nakato",
      village: "Namutamba Rural",
      location: "Mityana",
      phone: "+256 781 222333",
      farmSize: "2.0",
      cropTypes: ["Tomatoes", "Onions", "Green Peppers"],
      notes: "Nakato specializes in vegetable horticulture.",
      createdAt: new Date().toISOString(),
      status: "active",
    },
    {
      id: "farm_3",
      agentId: "usr_agent2",
      name: "Yusuf Kato",
      village: "Kikyusa Village",
      location: "Luweero",
      phone: "+256 754 555666",
      farmSize: "8.0",
      cropTypes: ["Pineapples", "Maize"],
      notes: "Kato is an experienced sweet organic pineapple farmer.",
      createdAt: new Date().toISOString(),
      status: "active",
    },
  ],
  products: [
    {
      id: "prod_1",
      farmerId: "farm_1",
      farmerName: "John Ssekandi",
      category: "Fruits & Bananas",
      name: "Organic Matooke (Green Bananas)",
      description: "Extra large green banana bunches.",
      price: 25000,
      stock: 45,
      unit: "Bunch",
      images: ["https://images.unsplash.com/photo-1566393028639-d108a42c46a7?auto=format&fit=crop&q=80&w=600"],
      availability: "immediate",
      createdAt: new Date().toISOString(),
    },
    {
      id: "prod_2",
      farmerId: "farm_1",
      farmerName: "John Ssekandi",
      category: "Grains & Seeds",
      name: "Arabica Coffee Beans (AA Grade)",
      description: "Sun-dried organic Arabica coffee beans.",
      price: 9000,
      stock: 350,
      unit: "kg",
      images: ["https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=600"],
      availability: "immediate",
      createdAt: new Date().toISOString(),
    },
    {
      id: "prod_3",
      farmerId: "farm_2",
      farmerName: "Grace Nakato",
      category: "Vegetables",
      name: "Fresh Vine-Ripened Tomatoes",
      description: "Firm, juicy red tomatoes.",
      price: 45000,
      stock: 12,
      unit: "Crate (25kg)",
      images: ["https://images.unsplash.com/photo-1595855759920-86582396756a?auto=format&fit=crop&q=80&w=600"],
      availability: "immediate",
      createdAt: new Date().toISOString(),
    },
    {
      id: "prod_4",
      farmerId: "farm_3",
      farmerName: "Yusuf Kato",
      category: "Fruits & Bananas",
      name: "Sweet Cayenne Pineapples",
      description: "Luweero's legendary honey-sweet pineapples.",
      price: 3500,
      stock: 500,
      unit: "Piece",
      images: ["https://images.unsplash.com/photo-1550258987-190a2d41a8ba?auto=format&fit=crop&q=80&w=600"],
      availability: "immediate",
      createdAt: new Date().toISOString(),
    },
  ],
  config: {
    farmerPercentage: 85,
    agentPercentage: 10,
    platformPercentage: 5,
  },
};